### ISSUE TITLE
能自选cdn库吗？或者多提供几个

### ISSUE THREAD

**Issue by adoin** [pd4d10/console-importer#21]
https://api.cdnjs.com/libraries 经常连接问题

**Comment by adoin** [comment]
很多库 没有上cdnjs，搜不到，至少unpkg  jsdeliver得要吧。。。

**Comment by rubickecho** [comment]
> 很多库 没有上cdnjs，搜不到，至少unpkg jsdeliver得要吧。。。

For advanced use, there are also two functions `$i.unpkg` and `$i.cdnjs` which could be used to import resources from specific CDN.

**Comment by adoin** [comment]
> > 很多库 没有上cdnjs，搜不到，至少unpkg jsdeliver得要吧。。。
> 
> For advanced use, there are also two functions `$i.unpkg` and `$i.cdnjs` which could be used to import resources from specific CDN.

😘😘😘
